// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package products

type _Entity interface {
	Is_Entity()
}

type Product struct {
	Upc    string  `json:"upc"`
	Name   *string `json:"name"`
	Price  *int    `json:"price"`
	Weight *int    `json:"weight"`
}

func (Product) Is_Entity() {}

type _Service struct {
	Sdl *string `json:"sdl"`
}
